name: UsualToneOfVoiceApp
options:
  bundleIdPrefix: local
  deploymentTarget:
    macOS: "14.0"
packages:
  WhisperBinary:
    path: Packages/WhisperBinary
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
schemes:
  UsualToneOfVoice:
    build:
      targets:
        UsualToneOfVoice: all
    run:
      config: Debug
    test:
      targets:
        - UsualToneOfVoiceTests
  UsualToneOfVoiceTests:
    build:
      targets:
        UsualToneOfVoice: all
        UsualToneOfVoiceTests: all
    test:
      targets:
        - UsualToneOfVoiceTests
targets:
  UsualToneOfVoice:
    type: application
    platform: macOS
    sources:
      - path: Sources/UsualToneOfVoice
        excludes:
          - Resources/**
    resources:
      - path: Sources/UsualToneOfVoice/Resources
      - path: Sources/UsualToneOfVoice/Assets.xcassets
    info:
      path: XcodeSupport/Info.plist
      properties:
        CFBundleDisplayName: "Usual Tone of Voice"
        LSApplicationCategoryType: "public.app-category.utilities"
        NSHighResolutionCapable: true
        NSMicrophoneUsageDescription: "Record audio to transcribe speech."
        NSPrincipalClass: "NSApplication"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: local.UsualToneOfVoice
    dependencies:
      - package: WhisperBinary
        product: whisper
  UsualToneOfVoiceTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/UsualToneOfVoiceTests
    dependencies:
      - target: UsualToneOfVoice
